-- Customers table
CREATE TABLE customers (
    customer_name varchar(255),
    customer_phone_no varchar(20),
    customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Salespersons table
CREATE TABLE salespersons (
    salesperson_name varchar(255) ,
 	  salesperson_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Manufacturers table
CREATE TABLE manufacturers (
    manufacturer_name varchar(255) ,
    manufacturer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- Cars table
CREATE TABLE cars (
    serial_number integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name varchar(255) NOT NULL,
    manufacturer_id integer,
    weight real,
    price real, 
    FOREIGN KEY(manufacturer_id) REFERENCES manufacturers(manufacturer_id) 
 		ON DELETE CASCADE
);

-- Transactions table
CREATE TABLE transactions (
    transaction_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	  transaction_datetime timestamp,
    customer_id integer,
    salesperson_id integer,
    car_serial_number integer UNIQUE,
	FOREIGN KEY(customer_id) REFERENCES customers(customer_id), 
	FOREIGN KEY(salesperson_id) REFERENCES salespersons(salesperson_id), 
	FOREIGN KEY(car_serial_number) REFERENCES cars(serial_number)
);

-- Insert values into the tables
INSERT INTO customers(customer_name, customer_phone_no) VALUES ('Anshu', '88911546');
INSERT INTO customers(customer_name, customer_phone_no) VALUES ('Jon', '828911546');
INSERT INTO customers(customer_name, customer_phone_no) VALUES ('Bob', '8891211546');
INSERT INTO customers(customer_name, customer_phone_no) VALUES ('Ravi', '838911546');
INSERT INTO customers(customer_name, customer_phone_no) VALUES ('Alex', '882911546');

INSERT INTO manufacturers(manufacturer_name) VALUES ('Porsche');
INSERT INTO manufacturers(manufacturer_name) VALUES ('Tesla');
INSERT INTO manufacturers(manufacturer_name) VALUES ('Kia');
INSERT INTO manufacturers(manufacturer_name) VALUES ('Jaguar');
INSERT INTO manufacturers(manufacturer_name) VALUES ('Honda');

INSERT INTO salespersons(salesperson_name) VALUES ('Kevin');
INSERT INTO salespersons(salesperson_name) VALUES ('Ron');
INSERT INTO salespersons(salesperson_name) VALUES ('Harry');
INSERT INTO salespersons(salesperson_name) VALUES ('Mira');

INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('A', 1, 12.3, 120);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('B', 2, 12.3, 300);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('A', 4, 12.3, 200);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('C', 3, 12.3, 450);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('A', 4, 12.3, 120);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('C', 5, 12.3, 100);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('D', 2, 12.3, 150);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('C', 3, 12.3, 120);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('B', 1, 12.3, 130);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('E', 3, 12.3, 140);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('D', 3, 12.3, 150);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('E', 3, 12.3, 120);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('B', 2, 12.3, 160);
INSERT INTO cars(model_name, manufacturer_id, weight, price) VALUES ('Q', 2, 12.3, 170);

INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 2, 4, 1);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-12-19 10:23:54', 2, 4, 2);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-10-19 10:23:54', 1, 3, 3);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-09-19 10:23:54', 4, 2, 4);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 1, 2, 5);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 2, 3, 6);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-07-19 10:23:54', 4, 1, 7);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 2, 3, 8);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 3, 3, 9);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 2, 3, 10);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-12-19 10:23:54', 4, 4, 11);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-11-19 10:23:54', 3, 1, 12);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-12-19 10:23:54', 1, 3, 13);
INSERT INTO transactions(transaction_datetime, customer_id, salesperson_id, car_serial_number)
VALUES ('2021-07-19 10:23:54', 2, 3, 14);
